// packages/core/src/errors/error-codes.enum.ts

export enum IntegrationErrorCode {
  // Auth errors (1xxx)
  OAUTH_NOT_CONFIGURED = 'AUTH_1001',
  OAUTH_EXPIRED = 'AUTH_1002',
  OAUTH_REVOKED = 'AUTH_1003',
  TOKEN_REFRESH_FAILED = 'AUTH_1004',
  INVALID_TOKEN = 'AUTH_1005',

  // Infrastructure errors (2xxx)
  CACHE_UNAVAILABLE = 'INFRA_2001',
  DATABASE_UNAVAILABLE = 'INFRA_2002',
  AUTH_SERVICE_UNAVAILABLE = 'INFRA_2003',
  NETWORK_TIMEOUT = 'INFRA_2004',

  // API errors (3xxx)
  API_RATE_LIMIT = 'API_3001',
  API_SERVER_ERROR = 'API_3002',
  API_BAD_REQUEST = 'API_3003',
  API_NOT_FOUND = 'API_3004',
  API_FORBIDDEN = 'API_3005',

  // Validation errors (4xxx)
  INVALID_ACCOUNT_ID = 'VALIDATION_4001',
  INVALID_PARAMETERS = 'VALIDATION_4002',
  MISSING_REQUIRED_FIELD = 'VALIDATION_4003',

  // Business logic errors (5xxx)
  ACCOUNT_SUSPENDED = 'BUSINESS_5001',
  FEATURE_NOT_AVAILABLE = 'BUSINESS_5002',
  QUOTA_EXCEEDED = 'BUSINESS_5003',
}
